trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  CONTAINER_NAME: 'taxpayer-number-test-container'

steps:
- task: FileTransform@1
  displayName: 'Substitute variables'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    fileType: 'json'
    targetFiles: '**/appsettings.json'

- script: 'docker build --force-rm -t $(CONTAINER_NAME)/chrome-install -f Dockerfiles/Dockerfile.chrome-install .'
  displayName: 'Install Google Chrome'
  
- script: 'docker build --force-rm -t $(CONTAINER_NAME)/build -f Dockerfiles/Dockerfile.build --build-arg CONTAINER_NAME=$(CONTAINER_NAME) .'
  displayName: 'Build app'

- script: 'docker build --force-rm -t $(CONTAINER_NAME)/test -f Dockerfiles/Dockerfile.test --build-arg CONTAINER_NAME=$(CONTAINER_NAME) .'
  displayName: 'Test app'
