trigger:
- main

pool:
  vmImage: ubuntu-20.04

variables:
  buildConfiguration: 'Release'
  containerName: 'taxpayer-number-test-container'

steps:
- task: FileTransform@1
  displayName: 'Substitute variables'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    fileType: 'json'
    targetFiles: '**/appsettings.json'

- powershell: Get-ChildItem -Path '$(System.DefaultWorkingDirectory)' -recurse
  displayName: 'Check file system'

- task: DockerInstaller@0
  displayName: 'Install Docker'
  inputs:
    dockerVersion: '17.09.0-ce'
    releaseType: stable

- script: 'docker build --force-rm -t $(containerName)/chrome-install -f Dockerfiles/Dockerfile.chrome-install .'
  displayName: 'Install Google Chrome'
  
- script: 'docker build --force-rm $(containerName) -t $(containerName)/build -f Dockerfiles/Dockerfile.build .'
  displayName: 'Build app'

- script: 'docker build --force-rm $(containerName) -t $(containerName)/test -f Dockerfiles/Dockerfile.test .'
  displayName: 'Test app'
